### ISSUE TITLE
Marshal an object to JSON using one method call

### ISSUE THREAD

**Issue by msdvoits** [Microsoft/Angara.Serialization#1]
As a user of Angara.Serialization.Json, I want to have a method which takes an object and a resolver and returns a Json as a string (and another method for back transformation), so that I could use Angara.Serialization.Json to convert .NET object to JSON with exact transformation, optimal array encoding and type-information available.

### Remarks
Now when I need to convert an object to JSON I should do two steps: conver object to InfoSet; convert InfoSet to Json. Meanwhile for me there is no need to know anything about the intermediate infoSet:
```F#
let infoSet = Angara.Serialization.ArtefactSerializer.Serialize resolver artefact
let json = Angara.Serialization.Json.Marshal(infoSet, None)
```
Why not the Angara.Serialization.Json to have one method for this common operation:
```F#
let json = Angara.Serialization.Json.FromObject(artefact, resolver)
```
And back:
```F#
let artefact = Angara.Serialization.Json.ToObject(json, resolver)
let artefact = Angara.Serialization.Json.ToObject<Artefact>(json, resolver)
```

**Comment by sergey-b-berezin** [comment]
Fixed by 3f1257209b141f3f714fc9fdc0c3caab296c6687.
